version: '3'

networks:
  student:

services:
  site:
    image: nginx:stable-alpine
    container_name: student_site
    hostname: 'student'
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/custom_nginx_proxy.conf:/etc/nginx/conf.d/custom_nginx_proxy.conf
    depends_on:
      - php
    networks:
      - student

  php:
    build:
      context: .
      dockerfile: docker/php.dockerfile
    container_name: student_php
    volumes:
      - ./:/var/www/html
      - ./docker/php_custom.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - 9000
    networks:
      - student

  composer:
    image: composer:2
    container_name: student_composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - student

  artisan:
    build:
      context: .
      dockerfile: docker/php.dockerfile
    container_name: student_artisan
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - student

  db:
    image: mariadb
    restart: unless-stopped
    container_name: student_database
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3310:3306
    environment:
      MYSQL_DATABASE: student_database
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - student

  npm:
    image: node:18-alpine
    container_name: student_npm
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - student
    command: sh -c "npm install && npm run build"
